### ISSUE TITLE
Конфликт требований и лицензии

### ISSUE THREAD

**Issue by 0xff00ff** [Khuzha/chatAdmin#5]
Уважаемый автор, у вас лицензией кода является дословное описание лицензии MIT
При этом в README вы указываете дополнительные требования.
Если хотите чтоб эти требования соблюдались, перенесите их в лицензионный текст (но тогда это уже не будет MIT)
Или не требуйте условий которые выходят за рамки описанной лицензии.

Спасибо.

**Comment by Khuzha** [comment]
Спасибо за замечание, исправил README в https://github.com/Khuzha/chatAdmin/commit/126be22e153ab6a9e4dcff245314490ddcc184a8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
